package dk.mwittrock.cpilint.model;

public enum Nameable {
	
	IFLOW_NAME,
	IFLOW_ID,
	CHANNEL_NAME,
	SENDER_CHANNEL_NAME,
	RECEIVER_CHANNEL_NAME,
	MAPPING_STEP_NAME,
	MESSAGE_MAPPING_STEP_NAME,
	XSLT_MAPPING_STEP_NAME,
	OPERATION_MAPPING_STEP_NAME,
	SCRIPT_STEP_NAME,
	GROOVY_SCRIPT_STEP_NAME,
	JS_SCRIPT_STEP_NAME,
	SENDER_NAME,
	RECEIVER_NAME,
	CONTENT_MODIFIER_STEP_NAME;
	
}
